// Vocabulary from Michel Thomas Foundation Egyptian Arabic course
// Fields: id, en (English), tl (transliteration), ar (Arabic script), cat (category), note, ex (example: {ar, tl, en})
window.VOCAB = [
  // ── Pronouns ──────────────────────────────────────────────────────────
  { id: "ana",    en: "I",             tl: "ana",      ar: "أنا",    cat: "Pronouns",
    ex: { ar: "أنا من مصر.",           tl: "ana min masr.",           en: "I'm from Egypt." } },
  { id: "inta",   en: "you (m)",       tl: "inta",     ar: "إنت",    cat: "Pronouns",
    ex: { ar: "إنت فين؟",              tl: "inta fein?",              en: "Where are you?" } },
  { id: "inti",   en: "you (f)",       tl: "inti",     ar: "إنتي",   cat: "Pronouns",
    ex: { ar: "إنتي عايزة إيه؟",       tl: "inti 3ayza eh?",          en: "What do you want?" } },
  { id: "huwwa",  en: "he",            tl: "huwwa",    ar: "هو",     cat: "Pronouns",
    ex: { ar: "هو هنا.",               tl: "huwwa hena.",             en: "He is here." } },
  { id: "hiyya",  en: "she",           tl: "hiyya",    ar: "هي",     cat: "Pronouns",
    ex: { ar: "هي كويسة.",             tl: "hiyya kwayyisa.",         en: "She's fine." } },
  { id: "ihna",   en: "we",            tl: "ihna",     ar: "إحنا",   cat: "Pronouns",
    ex: { ar: "إحنا في البيت.",        tl: "ihna fil beit.",          en: "We're at home." } },
  { id: "intu",   en: "you (pl)",      tl: "intu",     ar: "إنتوا",  cat: "Pronouns",
    ex: { ar: "إنتوا رايحين فين؟",     tl: "intu rayheen fein?",      en: "Where are you (all) going?" } },
  { id: "humma",  en: "they",          tl: "humma",    ar: "هما",    cat: "Pronouns",
    ex: { ar: "هما أصحابي.",           tl: "humma s7abi.",            en: "They are my friends." } },

  // ── Question Words ────────────────────────────────────────────────────
  { id: "eh",     en: "what",          tl: "eh",       ar: "إيه",    cat: "Questions",
    ex: { ar: "ده إيه؟",               tl: "da eh?",                  en: "What is this?" } },
  { id: "fein",   en: "where",         tl: "fein",     ar: "فين",    cat: "Questions",
    ex: { ar: "المطعم فين؟",           tl: "el-mat3am fein?",         en: "Where is the restaurant?" } },
  { id: "imta",   en: "when",          tl: "imta",     ar: "إمتى",   cat: "Questions",
    ex: { ar: "إمتى هتيجي؟",           tl: "imta hateegi?",           en: "When will you come?" } },
  { id: "leh",    en: "why",           tl: "leh",      ar: "ليه",    cat: "Questions",
    ex: { ar: "ليه كده؟",              tl: "leh keda?",               en: "Why like that?" } },
  { id: "izzay",  en: "how",           tl: "izzay",    ar: "إزّاي",  cat: "Questions",
    ex: { ar: "إزّاي حالك؟",           tl: "izzay 7alak?",            en: "How are you doing?" } },
  { id: "meen",   en: "who",           tl: "meen",     ar: "مين",    cat: "Questions",
    ex: { ar: "مين ده؟",               tl: "meen da?",                en: "Who is that?" } },
  { id: "bikam",  en: "how much",      tl: "bikam",    ar: "بكام",   cat: "Questions",
    ex: { ar: "ده بكام؟",              tl: "da bikam?",               en: "How much is this?" } },
  { id: "izzayak", en: "how are you (m)", tl: "izzayak", ar: "إزيك", cat: "Questions",
    ex: { ar: "إزيك النهاردة؟",        tl: "izzayak innaharda?",      en: "How are you today?" } },

  // ── Greetings & Politeness ────────────────────────────────────────────
  { id: "salam",  en: "hello / peace", tl: "salaam",   ar: "سلام",   cat: "Greetings",
    ex: { ar: "السلام عليكم.",         tl: "es-salaamu 3aleikum.",    en: "Peace be upon you." } },
  { id: "shukran", en: "thank you",    tl: "shukran",  ar: "شكراً",  cat: "Greetings",
    ex: { ar: "شكراً جداً.",           tl: "shukran giddan.",         en: "Thank you very much." } },
  { id: "3afwan", en: "you're welcome", tl: "3afwan",  ar: "عفواً",  cat: "Greetings",
    ex: { ar: "عفواً، مافيش مشكلة.",   tl: "3afwan, mafeesh mushkila.", en: "You're welcome, no problem." } },
  { id: "min-fadlak", en: "please (m)", tl: "min fadlak", ar: "من فضلك", cat: "Greetings",
    ex: { ar: "قهوة من فضلك.",         tl: "ahwa min fadlak.",        en: "A coffee please." } },
  { id: "law-samaht", en: "excuse me / please", tl: "law samaht", ar: "لو سمحت", cat: "Greetings",
    ex: { ar: "لو سمحت، فين الحمام؟",  tl: "law samaht, fein el-7ammam?", en: "Excuse me, where's the bathroom?" } },
  { id: "aasef",  en: "sorry (m)",     tl: "aasef",    ar: "آسف",    cat: "Greetings",
    ex: { ar: "آسف، أنا متأخر.",       tl: "aasef, ana mit'akhar.",   en: "Sorry, I'm late." } },
  { id: "tamam",  en: "fine / ok",     tl: "tamam",    ar: "تمام",   cat: "Greetings",
    ex: { ar: "تمام، ماشي.",           tl: "tamam, maashi.",          en: "Fine, alright." } },

  // ── Connectors ────────────────────────────────────────────────────────
  { id: "w",      en: "and",           tl: "wi",       ar: "و",      cat: "Connectors",
    ex: { ar: "شاي وقهوة.",            tl: "shai wi ahwa.",           en: "Tea and coffee." } },
  { id: "bass",   en: "but / only",    tl: "bass",     ar: "بس",     cat: "Connectors",
    ex: { ar: "عايز، بس مش دلوقتي.",   tl: "3ayez, bass mish dilwa'ti.", en: "I want to, but not now." } },
  { id: "walla",  en: "or",            tl: "walla",    ar: "ولا",    cat: "Connectors",
    ex: { ar: "شاي ولا قهوة؟",         tl: "shai walla ahwa?",        en: "Tea or coffee?" } },
  { id: "3ashan", en: "because / in order to", tl: "3ashan", ar: "عشان", cat: "Connectors",
    ex: { ar: "جيت عشان أشوفك.",       tl: "geet 3ashan ashoofak.",   en: "I came to see you." } },
  { id: "3ashan-keda", en: "that's why", tl: "3ashan keda", ar: "عشان كده", cat: "Connectors",
    ex: { ar: "تعبان، عشان كده مش هاجي.", tl: "ta3baan, 3ashan keda mish hagi.", en: "I'm tired, that's why I'm not coming." } },
  { id: "ya3ni",  en: "I mean / sort of", tl: "ya3ni", ar: "يعني",   cat: "Connectors",
    ex: { ar: "كويس؟ يعني.",           tl: "kwayyes? ya3ni.",         en: "Good? Sort of." } },

  // ── Modal / Useful Building Blocks ────────────────────────────────────
  { id: "mumkin", en: "possible / can I", tl: "mumkin", ar: "ممكن",  cat: "Modals",
    ex: { ar: "ممكن مية من فضلك؟",     tl: "mumkin mayya min fadlak?", en: "Can I have water please?" } },
  { id: "lazem",  en: "must / have to", tl: "laazem",  ar: "لازم",   cat: "Modals",
    ex: { ar: "لازم أمشي دلوقتي.",     tl: "laazem amshi dilwa'ti.",  en: "I must leave now." } },
  { id: "3ayez",  en: "I want (m)",    tl: "3ayez",    ar: "عايز",   cat: "Modals",
    ex: { ar: "أنا عايز أروح البيت.",  tl: "ana 3ayez aroo7 el-beit.", en: "I want to go home." } },
  { id: "3ayza",  en: "I want (f)",    tl: "3ayza",    ar: "عايزة",  cat: "Modals",
    ex: { ar: "أنا عايزة أشرب شاي.",   tl: "ana 3ayza ashrab shai.",  en: "I want to drink tea." } },
  { id: "mish",   en: "not (negation)", tl: "mish",    ar: "مش",     cat: "Modals",
    ex: { ar: "أنا مش عارف.",          tl: "ana mish 3aarif.",        en: "I don't know." } },
  { id: "3andi",  en: "I have",        tl: "3andi",    ar: "عندي",   cat: "Modals",
    ex: { ar: "عندي عربية.",           tl: "3andi 3arabeyya.",        en: "I have a car." } },
  { id: "mafeesh", en: "there isn't",  tl: "mafeesh",  ar: "مافيش",  cat: "Modals",
    ex: { ar: "مافيش مشكلة.",          tl: "mafeesh mushkila.",       en: "No problem." } },
  { id: "feeh",   en: "there is",      tl: "feeh",     ar: "فيه",    cat: "Modals",
    ex: { ar: "فيه ناس كتير.",         tl: "feeh naas kiteer.",       en: "There are many people." } },

  // ── Common Verbs (I-form) ─────────────────────────────────────────────
  { id: "aroh",   en: "to go",         tl: "aroo7",    ar: "أروح",   cat: "Verbs",
    ex: { ar: "بروح الشغل الساعة تسعة.", tl: "baroo7 el-shoghl es-sa3a tes3a.", en: "I go to work at 9." } },
  { id: "agi",    en: "to come",       tl: "agi",      ar: "أجي",    cat: "Verbs",
    ex: { ar: "هجي بكرة.",             tl: "hagi bukra.",             en: "I'll come tomorrow." } },
  { id: "aakul",  en: "to eat",        tl: "aakul",    ar: "آكل",    cat: "Verbs",
    ex: { ar: "بحب آكل عيش.",          tl: "ba7ebb aakul 3eish.",     en: "I love to eat bread." } },
  { id: "ashrab", en: "to drink",      tl: "ashrab",   ar: "أشرب",   cat: "Verbs",
    ex: { ar: "بشرب قهوة كل الصبح.",   tl: "bashrab ahwa kull es-sob7.", en: "I drink coffee every morning." } },
  { id: "a3ref",  en: "to know",       tl: "a3raf",    ar: "أعرف",   cat: "Verbs",
    ex: { ar: "أنا عارف الاسم.",       tl: "ana 3aarif el-ism.",      en: "I know the name." } },
  { id: "afham",  en: "to understand", tl: "afham",    ar: "أفهم",   cat: "Verbs",
    ex: { ar: "مش فاهم، تاني مرة؟",    tl: "mish faahim, tani marra?", en: "I don't understand, one more time?" } },
  { id: "ashoof", en: "to see",        tl: "ashoof",   ar: "أشوف",   cat: "Verbs",
    ex: { ar: "شفت الفيلم أمبارح.",    tl: "shoft el-film imbaare7.", en: "I saw the film yesterday." } },
  { id: "a3mel",  en: "to do / make",  tl: "a3mel",    ar: "أعمل",   cat: "Verbs",
    ex: { ar: "بتعمل إيه؟",            tl: "bti3mel eh?",             en: "What are you doing?" } },
  { id: "a2ool",  en: "to say",        tl: "a'ool",    ar: "أقول",   cat: "Verbs",
    ex: { ar: "بيقول إنه تعبان.",      tl: "biy'ool innoh ta3baan.",  en: "He says he's tired." } },
  { id: "asma3",  en: "to hear",       tl: "asma3",    ar: "أسمع",   cat: "Verbs",
    ex: { ar: "بسمع موسيقى.",          tl: "basma3 mooseeqa.",        en: "I'm listening to music." } },
  { id: "aftikir", en: "to think / remember", tl: "aftikir", ar: "أفتكر", cat: "Verbs",
    ex: { ar: "بفتكر إنك حلو.",        tl: "baftikir innak 7ilw.",    en: "I think you're nice." } },
  { id: "astanna", en: "to wait",      tl: "astanna",  ar: "أستنى",  cat: "Verbs",
    ex: { ar: "استنى دقيقة.",          tl: "istanna daqee'a.",        en: "Wait a minute." } },
  { id: "as2al",  en: "to ask",        tl: "as'al",    ar: "أسأل",   cat: "Verbs",
    ex: { ar: "ممكن أسألك سؤال؟",      tl: "mumkin as'alak su'aal?",  en: "Can I ask you a question?" } },
  { id: "ashtaghal", en: "to work",    tl: "ashtaghal", ar: "أشتغل", cat: "Verbs",
    ex: { ar: "بشتغل في القاهرة.",     tl: "bashtaghal fil qaahira.", en: "I work in Cairo." } },
  { id: "anam",   en: "to sleep",      tl: "anaam",    ar: "أنام",   cat: "Verbs",
    ex: { ar: "بنام بدري.",            tl: "banaam badri.",           en: "I sleep early." } },
  { id: "atkallem", en: "to speak",    tl: "atkallem", ar: "أتكلّم",  cat: "Verbs",
    ex: { ar: "بتكلم عربي شوية.",      tl: "batkallem 3arabi shuwayya.", en: "I speak a little Arabic." } },
  { id: "ashteri", en: "to buy",       tl: "ashteri",  ar: "أشتري",  cat: "Verbs",
    ex: { ar: "هشتري عيش من السوق.",   tl: "hashteri 3eish min es-soo'.", en: "I'll buy bread from the market." } },
  { id: "adfa3",  en: "to pay",        tl: "adfa3",    ar: "أدفع",   cat: "Verbs",
    ex: { ar: "أنا هدفع.",             tl: "ana hadfa3.",             en: "I'll pay." } },

  // ── Food & Drink ──────────────────────────────────────────────────────
  { id: "ahwa",   en: "coffee",        tl: "ahwa",     ar: "قهوة",   cat: "Food & Drink",
    ex: { ar: "قهوة بسكر، من فضلك.",   tl: "ahwa bi-sokkar, min fadlak.", en: "Coffee with sugar, please." } },
  { id: "shai",   en: "tea",           tl: "shai",     ar: "شاي",    cat: "Food & Drink",
    ex: { ar: "بحب الشاي باللبن.",     tl: "ba7ebb esh-shai bil-laban.", en: "I love tea with milk." } },
  { id: "mayya",  en: "water",         tl: "mayya",    ar: "ميّة",   cat: "Food & Drink",
    ex: { ar: "ميّة باردة من فضلك.",   tl: "mayya baarda min fadlak.", en: "Cold water please." } },
  { id: "3eish",  en: "bread",         tl: "3eish",    ar: "عيش",    cat: "Food & Drink",
    ex: { ar: "العيش المصري لذيذ.",    tl: "el-3eish el-masri laziz.", en: "Egyptian bread is delicious." } },
  { id: "akl",    en: "food",          tl: "akl",      ar: "أكل",    cat: "Food & Drink",
    ex: { ar: "الأكل هنا كويس.",       tl: "el-akl hena kwayyes.",    en: "The food here is good." } },
  { id: "sokkar", en: "sugar",         tl: "sokkar",   ar: "سكر",    cat: "Food & Drink",
    ex: { ar: "من غير سكر، من فضلك.",  tl: "min gheir sokkar, min fadlak.", en: "Without sugar, please." } },
  { id: "laban",  en: "milk",          tl: "laban",    ar: "لبن",    cat: "Food & Drink",
    ex: { ar: "قهوة باللبن.",          tl: "ahwa bil-laban.",         en: "Coffee with milk." } },

  // ── Places ────────────────────────────────────────────────────────────
  { id: "beit",   en: "house / home",  tl: "beit",     ar: "بيت",    cat: "Places",
    ex: { ar: "أنا في البيت.",         tl: "ana fil beit.",           en: "I'm at home." } },
  { id: "shoghl", en: "work / job",    tl: "shoghl",   ar: "شغل",    cat: "Places",
    ex: { ar: "الشغل تعبان النهاردة.", tl: "esh-shoghl ta3baan innaharda.", en: "Work is tough today." } },
  { id: "mat3am", en: "restaurant",    tl: "mat3am",   ar: "مطعم",   cat: "Places",
    ex: { ar: "فيه مطعم كويس قريب.",   tl: "feeh mat3am kwayyes ureyyeb.", en: "There's a good restaurant nearby." } },
  { id: "fondo2", en: "hotel",         tl: "fondo'",   ar: "فندق",   cat: "Places",
    ex: { ar: "الفندق فين؟",           tl: "el-fondo' fein?",         en: "Where is the hotel?" } },
  { id: "mataar", en: "airport",       tl: "mataar",   ar: "مطار",   cat: "Places",
    ex: { ar: "رايح المطار.",          tl: "raaye7 el-mataar.",       en: "I'm going to the airport." } },
  { id: "soo2",   en: "market",        tl: "soo'",     ar: "سوق",    cat: "Places",
    ex: { ar: "السوق زحمة.",           tl: "es-soo' za7ma.",          en: "The market is crowded." } },
  { id: "3arabeyya", en: "car",        tl: "3arabeyya", ar: "عربية", cat: "Places",
    ex: { ar: "العربية بره.",          tl: "el-3arabeyya barra.",     en: "The car is outside." } },

  // ── People / Family ───────────────────────────────────────────────────
  { id: "sahib",  en: "friend (m)",    tl: "sa7eb",    ar: "صاحب",   cat: "People",
    ex: { ar: "ده صاحبي.",             tl: "da sa7bi.",               en: "This is my friend." } },
  { id: "sit",    en: "woman / lady",  tl: "sitt",     ar: "ست",     cat: "People",
    ex: { ar: "الست دي أمي.",          tl: "es-sitt di ommi.",        en: "That lady is my mother." } },
  { id: "ragel",  en: "man",           tl: "raagel",   ar: "راجل",   cat: "People",
    ex: { ar: "الراجل ده لطيف.",       tl: "er-raagel da lateef.",    en: "That man is nice." } },
  { id: "walad",  en: "boy",           tl: "walad",    ar: "ولد",    cat: "People",
    ex: { ar: "الولد بيلعب.",          tl: "el-walad biyla3ab.",      en: "The boy is playing." } },
  { id: "bint",   en: "girl / daughter", tl: "bint",   ar: "بنت",    cat: "People",
    ex: { ar: "بنتي عندها ٦ سنين.",    tl: "binti 3andaha sitt sneen.", en: "My daughter is 6 years old." } },
  { id: "ibn",    en: "son",           tl: "ibn",      ar: "ابن",    cat: "People",
    ex: { ar: "ابني في المدرسة.",      tl: "ibni fil madrasa.",       en: "My son is at school." } },
  { id: "omm",    en: "mother",        tl: "omm",      ar: "أم",     cat: "People",
    ex: { ar: "أمي بتطبخ.",            tl: "ommi bit-tobokh.",        en: "My mom is cooking." } },
  { id: "abb",    en: "father",        tl: "abb",      ar: "أب",     cat: "People",
    ex: { ar: "أبويا شغال.",           tl: "abooya shaghghaal.",      en: "My dad is at work." } },

  // ── Adjectives ────────────────────────────────────────────────────────
  { id: "kwayyes", en: "good / well",  tl: "kwayyes",  ar: "كويّس",  cat: "Adjectives",
    ex: { ar: "أنا كويّس، الحمد لله.", tl: "ana kwayyes, el7amdulillah.", en: "I'm well, thank God." } },
  { id: "wihish", en: "bad",           tl: "wi7esh",   ar: "وحش",    cat: "Adjectives",
    ex: { ar: "الجو وحش النهاردة.",    tl: "el-gaww wi7esh innaharda.", en: "The weather is bad today." } },
  { id: "kibeer", en: "big",           tl: "kibeer",   ar: "كبير",   cat: "Adjectives",
    ex: { ar: "البيت كبير.",           tl: "el-beit kibeer.",         en: "The house is big." } },
  { id: "sughayyar", en: "small",      tl: "sughayyar", ar: "صغيّر", cat: "Adjectives",
    ex: { ar: "قهوة صغيرة، من فضلك.",  tl: "ahwa sughayyara, min fadlak.", en: "A small coffee, please." } },
  { id: "ghaali", en: "expensive",     tl: "ghaali",   ar: "غالي",   cat: "Adjectives",
    ex: { ar: "ده غالي أوي.",          tl: "da ghaali awi.",          en: "That's very expensive." } },
  { id: "rikhees", en: "cheap",        tl: "rikhees",  ar: "رخيص",   cat: "Adjectives",
    ex: { ar: "السوق ده رخيص.",        tl: "es-soo' da rikhees.",     en: "This market is cheap." } },
  { id: "gedeed", en: "new",           tl: "gedeed",   ar: "جديد",   cat: "Adjectives",
    ex: { ar: "عندي عربية جديدة.",     tl: "3andi 3arabeyya gedeeda.", en: "I have a new car." } },
  { id: "adeem",  en: "old (thing)",   tl: "adeem",    ar: "قديم",   cat: "Adjectives",
    ex: { ar: "الكتاب ده قديم.",       tl: "el-kitaab da adeem.",     en: "This book is old." } },
  { id: "sokhn",  en: "hot",           tl: "sokhn",    ar: "سخن",    cat: "Adjectives",
    ex: { ar: "الشاي سخن.",            tl: "esh-shai sokhn.",         en: "The tea is hot." } },
  { id: "baared", en: "cold",          tl: "baared",   ar: "بارد",   cat: "Adjectives",
    ex: { ar: "ميّة باردة، لو سمحت.",  tl: "mayya baarda, law samaht.", en: "Cold water, please." } },
  { id: "gameel", en: "beautiful / nice", tl: "gameel", ar: "جميل",  cat: "Adjectives",
    ex: { ar: "المكان جميل.",          tl: "el-makaan gameel.",       en: "The place is beautiful." } },
  { id: "ta3baan", en: "tired / sick", tl: "ta3baan",  ar: "تعبان",  cat: "Adjectives",
    ex: { ar: "أنا تعبان شوية.",       tl: "ana ta3baan shuwayya.",   en: "I'm a bit tired." } },

  // ── Time ──────────────────────────────────────────────────────────────
  { id: "dilwa2ti", en: "now",         tl: "dilwa'ti", ar: "دلوقتي", cat: "Time",
    ex: { ar: "لازم أروح دلوقتي.",     tl: "laazem aroo7 dilwa'ti.",  en: "I must go now." } },
  { id: "ba3dein", en: "later",        tl: "ba3dein",  ar: "بعدين",  cat: "Time",
    ex: { ar: "نتكلم بعدين.",          tl: "netkallem ba3dein.",      en: "Let's talk later." } },
  { id: "innaharda", en: "today",      tl: "innaharda", ar: "النهاردة", cat: "Time",
    ex: { ar: "النهاردة الجمعة.",      tl: "innaharda el-gum3a.",     en: "Today is Friday." } },
  { id: "bukra",  en: "tomorrow",      tl: "bukra",    ar: "بكرة",   cat: "Time",
    ex: { ar: "أشوفك بكرة.",           tl: "ashoofak bukra.",         en: "See you tomorrow." } },
  { id: "imbareh", en: "yesterday",    tl: "imbaare7", ar: "إمبارح", cat: "Time",
    ex: { ar: "كنت هنا إمبارح.",       tl: "kunt hena imbaare7.",     en: "I was here yesterday." } },
  { id: "sana",   en: "year",          tl: "sana",     ar: "سنة",    cat: "Time",
    ex: { ar: "من سنة.",               tl: "min sana.",               en: "A year ago." } },
  { id: "shahr",  en: "month",         tl: "shahr",    ar: "شهر",    cat: "Time",
    ex: { ar: "الشهر ده مشغول.",       tl: "esh-shahr da mashghool.", en: "This month is busy." } },
  { id: "yom",    en: "day",           tl: "yom",      ar: "يوم",    cat: "Time",
    ex: { ar: "يوم جميل!",             tl: "yom gameel!",             en: "A beautiful day!" } },
  { id: "sa3a",   en: "hour / clock",  tl: "saa3a",    ar: "ساعة",   cat: "Time",
    ex: { ar: "الساعة كام؟",           tl: "es-saa3a kaam?",          en: "What time is it?" } },

  // ── Quantities & Location ─────────────────────────────────────────────
  { id: "kiteer", en: "a lot / much",  tl: "kiteer",   ar: "كتير",   cat: "Quantities",
    ex: { ar: "شكراً كتير.",           tl: "shukran kiteer.",         en: "Thanks a lot." } },
  { id: "shuwayya", en: "a little",    tl: "shuwayya", ar: "شويّة",  cat: "Quantities",
    ex: { ar: "بتكلم عربي شويّة.",     tl: "batkallem 3arabi shuwayya.", en: "I speak a little Arabic." } },
  { id: "awi",    en: "very",          tl: "awi",      ar: "أوي",    cat: "Quantities",
    ex: { ar: "الجو حر أوي.",          tl: "el-gaww 7arr awi.",       en: "The weather is very hot." } },
  { id: "hena",   en: "here",          tl: "hena",     ar: "هنا",    cat: "Location",
    ex: { ar: "استنى هنا.",            tl: "istanna hena.",           en: "Wait here." } },
  { id: "hinaak", en: "there",         tl: "hinaak",   ar: "هناك",   cat: "Location",
    ex: { ar: "شوف هناك.",             tl: "shoof hinaak.",           en: "Look over there." } },
  { id: "gamb",   en: "next to",       tl: "gamb",     ar: "جنب",    cat: "Location",
    ex: { ar: "البنك جنب الفندق.",     tl: "el-bank gamb el-fondo'.", en: "The bank is next to the hotel." } },
  { id: "wara",   en: "behind",        tl: "wara",     ar: "ورا",    cat: "Location",
    ex: { ar: "ورا البيت.",            tl: "wara el-beit.",           en: "Behind the house." } },
  { id: "oddam",  en: "in front of",   tl: "oddaam",   ar: "قدّام",  cat: "Location",
    ex: { ar: "قدّامك على طول.",       tl: "oddaamak 3ala tool.",     en: "Straight ahead of you." } },

  // ── Numbers ───────────────────────────────────────────────────────────
  { id: "wahed",  en: "one",           tl: "waa7ed",   ar: "واحد",   cat: "Numbers",
    ex: { ar: "قهوة واحدة.",           tl: "ahwa wa7da.",             en: "One coffee." } },
  { id: "itnein", en: "two",           tl: "itnein",   ar: "اتنين",  cat: "Numbers",
    ex: { ar: "اتنين شاي.",            tl: "itnein shai.",            en: "Two teas." } },
  { id: "talata", en: "three",         tl: "talaata",  ar: "تلاتة",  cat: "Numbers",
    ex: { ar: "عندي تلاتة إخوات.",     tl: "3andi talaata ikhwaat.",  en: "I have three siblings." } },
  { id: "arba3a", en: "four",          tl: "arba3a",   ar: "أربعة",  cat: "Numbers",
    ex: { ar: "الساعة أربعة.",         tl: "es-saa3a arba3a.",        en: "It's four o'clock." } },
  { id: "khamsa", en: "five",          tl: "khamsa",   ar: "خمسة",   cat: "Numbers",
    ex: { ar: "خمسة جنيه بس.",         tl: "khamsa gineh bass.",      en: "Only five pounds." } },
  { id: "3ashra", en: "ten",           tl: "3ashara",  ar: "عشرة",   cat: "Numbers",
    ex: { ar: "عشرة دقايق.",           tl: "3ashara da'ayi'.",        en: "Ten minutes." } },
];
